services:
  bot:
    build:
      context: .
    restart: unless-stopped
    container_name: csihu
    env_file:
      - .env
    depends_on:
      - db
      - chrome
    ports:
      - "9952:9952"

  db:
    image: postgres:17.4-alpine
    container_name: csihu-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: csihu-chrome
    init: true
    restart: unless-stopped
    hostname: chrome
    privileged: true
    shm_size: 2g
    ports:
      - "5900:5900"
      - "4444:4444"

volumes:
  postgres-data:
